import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Wiki sidebar configuration for Hake's Homelab.
 * 
 * The sidebar is autogenerated from the docs directory structure.
 * Categories are created from subdirectories (overview, hosts, equipment, services).
 * 
 * @see https://docusaurus.io/docs/sidebar
 */
const sidebars: SidebarsConfig = {
  // Autogenerate sidebar from docs folder structure
  wikiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
